OUTPUT_PATH="SET_OUTPUT_PATH"
TRAINING_DATA_PATH="SET_TRAINING_DATA_PATH"
TEST_DATA_PATH="SET_TEST_DATA_PATH"
EPOCHS="SET_EPOCH_AMOUNT"
MINIBATCH_SIZE="SET_MINI_BATCH_AMOUNT"
python scripts/estimator_sur_train.py -i "${TRAINING_DATA_PATH}" -o "${OUTPUT_PATH}"  -l ./index -e $EPOCHS -sn estimator_spec -b $MINIBATCH_SIZE -td $TEST_DATA_PATH
